# Generated by Django 5.1.7 on 2025-04-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('poly_id', models.CharField(max_length=255)),
                ('center', models.CharField(max_length=50)),
                ('area', models.FloatField()),
            ],
        ),
    ]
